- name:             Ethereum Deposit Wallet
  blockchain_key:   eth-mainnet
  currency_id:      eth
  # Address where deposits will be collected to.
  address:          'changeme'  # IMPORTANT: Always wrap this value in quotes!
  kind:             deposit    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1          # Number of signatures required for performing withdraw.
  max_balance:      0.0
  status:           active
  gateway:          infurad  # Gateway client name.
  settings:
    #
    # infurad gateway client settings.
    uri:          http://user:password@127.0.0.1:19332
    sign_uri:     http://infura_cli:4545
    password:     password

- name:             Ethereum Hot Wallet
  blockchain_key:   eth-mainnet
  currency_id:      eth
  # Address where deposits will be collected to.
  address:          'changeme'  # IMPORTANT: Always wrap this value in quotes!
  kind:             hot     # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      5.0
  status:           active
  gateway:          infurad   # Gateway client name.
  settings:
    #
    # infurad gateway client settings.
    uri:          http://user:password@127.0.0.1:19332
    sign_uri:     http://infura_cli:4545
    password:     password

- name:             Ethereum Warm Wallet
  blockchain_key:   eth-mainnet
  currency_id:      eth
  # Address where deposits will be collected to.
  address:          'changeme'  # IMPORTANT: Always wrap this value in quotes!
  kind:             warm    # Wallet kind (deposit, hot, warm, cold or fee).
  nsig:             1       # Number of signatures required for performing withdraw.
  max_balance:      50.0
  status:           active
  gateway:          infurad   # Gateway client name.
  settings:
    #
    # infurad gateway client settings.
    uri:          http://user:password@127.0.0.1:19332
    sign_uri:     http://infura_cli:4545
    password:     password
